import { ROLES } from './roles.js';

export const PERMISSIONS = Object.freeze({
  // Cases
  CASE_VIEW: 'CASE_VIEW',
  CASE_VIEW_ASSIGNED: 'CASE_VIEW_ASSIGNED',
  CASE_CREATE: 'CASE_CREATE',
  CASE_UPDATE: 'CASE_UPDATE',
  CASE_ASSIGN: 'CASE_ASSIGN',

  // Evidence
  EVIDENCE_VIEW: 'EVIDENCE_VIEW',
  EVIDENCE_CREATE: 'EVIDENCE_CREATE',
  EVIDENCE_UPDATE: 'EVIDENCE_UPDATE',
  EVIDENCE_UPLOAD: 'EVIDENCE_UPLOAD',
  EVIDENCE_STATUS_CHANGE: 'EVIDENCE_STATUS_CHANGE',
  EVIDENCE_VERIFY: 'EVIDENCE_VERIFY',

  // Audit & Compliance
  AUDIT_VIEW: 'AUDIT_VIEW',
  COMPLIANCE_VIEW: 'COMPLIANCE_VIEW',

  // User & Identity Management
  USER_VIEW: 'USER_VIEW',
  USER_MANAGE: 'USER_MANAGE',
  USER_ROLE_ASSIGN: 'USER_ROLE_ASSIGN',
  USER_SUSPEND: 'USER_SUSPEND',
  USER_REACTIVATE: 'USER_REACTIVATE',
  USER_DEACTIVATE: 'USER_DEACTIVATE',

  // Access Requests
  ACCESS_REQUEST_VIEW: 'ACCESS_REQUEST_VIEW',
  ACCESS_REQUEST_REVIEW: 'ACCESS_REQUEST_REVIEW',

  // System
  SYSTEM_MANAGE: 'SYSTEM_MANAGE',
});

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.INVESTIGATING_OFFICER]: Object.freeze([
    PERMISSIONS.CASE_VIEW_ASSIGNED,
    PERMISSIONS.CASE_CREATE,
    PERMISSIONS.CASE_UPDATE,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.EVIDENCE_UPLOAD,
    PERMISSIONS.EVIDENCE_VERIFY,
  ]),

  [ROLES.FORENSIC_OFFICER]: Object.freeze([
    PERMISSIONS.CASE_VIEW_ASSIGNED,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.EVIDENCE_UPLOAD,
    PERMISSIONS.EVIDENCE_VERIFY,
  ]),

  [ROLES.COURT_CLERK]: Object.freeze([
    PERMISSIONS.CASE_VIEW_ASSIGNED,
    PERMISSIONS.CASE_UPDATE,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_STATUS_CHANGE,
  ]),

  [ROLES.AUDITOR]: Object.freeze([
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_VERIFY,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
  ]),

  [ROLES.ADMIN]: Object.freeze([
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.USER_ROLE_ASSIGN,
    PERMISSIONS.USER_SUSPEND,
    PERMISSIONS.USER_REACTIVATE,
    PERMISSIONS.USER_DEACTIVATE,
    PERMISSIONS.ACCESS_REQUEST_VIEW,
    PERMISSIONS.ACCESS_REQUEST_REVIEW,
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.CASE_ASSIGN,
    PERMISSIONS.SYSTEM_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.COMPLIANCE_VIEW,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_VERIFY,
    PERMISSIONS.EVIDENCE_STATUS_CHANGE,
    PERMISSIONS.CASE_UPDATE,
  ]),
});
